---
title: "Cellchat for CXCR collab"
output: html_document
date: "2024-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}
library(Seurat)
library(tidyverse)
library(CellChat)
library(patchwork)
library(svglite)
library(ggalluvial)
library(NMF)
library(reticulate)
options(stringsAsFactors = FALSE)
```

```{r set seed and project name, warning=F, message=F}
set.seed(1234)
proj_name <- "FLCvNML"
```

```{r}
cellchat <- readRDS("./fullDataset/rds/scRNA_FLCnew-1-alternate.rds")
```

```{r}
cellchat <- computeCommunProb(cellchat, type = "truncatedMean", population.size = TRUE, trim = 0.15)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
saveRDS(cellchat, "./revisedDataset/rds/scRNA_FLCnew-truncated0.15.rds")
cellchat <- readRDS("./revisedDataset/rds/scRNA_FLCnew-truncated0.15.rds")
```

```{r}
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
```

```{r}
levels = c("Liver epithelial cells 1","Liver epithelial cells 2", "Liver epithelial cells 3", "Liver epithelial cells 4", "Liver epithelial cells 5", "Liver epithelial cells 6", "Endothelial cells", "Stellate cells", "Neutrophils and macrophages", "Lymphocytes", "Cholangiocyte cells", "Unknown") # set factor
cellchat <- updateClusterLabels(cellchat, new.order = levels)
levels(cellchat@idents)
```

```{r Calculate the aggregated cell-cell communication network}
dir.create("./revisedDataset/cellChat/FLCnew/trunc0.15")
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents)) # number of cells in each cell group
levels(cellchat@idents)
```

```{r}
cols <- c("Liver epithelial cells 1" = "#0072B2",
             "Liver epithelial cells 2" = "#cab2d6",
             "Endothelial cells" = "#6a3d9a",
             "Liver epithelial cells 3" = "#DDCC77",
             "Liver epithelial cells 4" = "#ff7f00",
             "Stellate cells" = "#33a02c",
             "Liver epithelial cells 5" = "#AA4499",
             "Cholangiocyte cells" = "#CC6677",
             "Neutrophils and macrophages" = "#44AA99",
             "Lymphocytes" = "#8C87E6",
             "Liver epithelial cells 6" = "#FF6B6B",
             "Unknown" = "#b15928")
```

```{r}
df.net <- subsetCommunication(cellchat)
df_net <- subsetCommunication(cellchat, signaling = c(unique(df.net$pathway_name)), slot.name = "net")
df_net
write.csv(df.net, "./revisedDataset/cellChat/FLCnew/trunc0.15/cellChat-allInferredCommunications.csv")
write.csv(df_net, "./revisedDataset/cellChat/FLCnew/trunc0.15/cellChat-upregulatedPathways-ofInterest.csv")
```

### Part IV: Systems analysis of cell-cell communication network

```{r}
ptm = Sys.time()
# Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
# Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups
```

```{r}
# Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
gg1 <- netAnalysis_signalingRole_scatter(cellchat)
#> Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
# Signaling role analysis on the cell-cell communication networks of interest
gg2 <- netAnalysis_signalingRole_scatter(cellchat, signaling = c("PERIOSTIN", "VEGFA", "TGFb", "PDGF", "FGF", "CALCR"))
#> Signaling role analysis on the cell-cell communication network from user's input
gg1 + gg2
png(file = "./revisedDataset/cellChat/FLCnew/trunc0.15/SystemsLevelAnalysis/SignalingRolesScatter.png", width = 5, height = 4, units = "in", res = 600)
gg1
dev.off()
```

```{r}
selectK(cellchat, pattern = "outgoing")
```

```{r}
nPatterns = 2
png(file ="./revisedDataset/cellChat/FLCnew/trunc0.15/SystemsLevelAnalysis/OutgoingPatterns.png", width = 10, height = 3, units = "in", res = 600)
cellchat <- identifyCommunicationPatterns(cellchat, pattern = "outgoing", k = nPatterns)
dev.off()
```

```{r}
selectK(cellchat, pattern = "incoming")
```

```{r}
nPatterns = 2
png(file ="./revisedDataset/cellChat/FLCnew/plots/SystemsLevelAnalysis/IncomingPatterns.png", width = 10, height = 3, units = "in", res = 600)
cellchat <- identifyCommunicationPatterns(cellchat, pattern = "incoming", k = nPatterns)
dev.off()
```

### Manifold and classification learning analysis of signaling networks

```{r}
use_python("/home/af547/miniconda3/bin/python")
cellchat <- computeNetSimilarity(cellchat, type = "functional")
cellchat <- netEmbedding(cellchat, type = "functional")
#> Manifold learning of the signaling networks for a single dataset
cellchat <- netClustering(cellchat, type = "functional", do.parallel = FALSE)
#> Classification learning of the signaling networks for a single dataset
# Visualization in 2D-space
netVisual_embedding(cellchat, type = "functional", label.size = 3.5)
```

```{r}
cellchat <- computeNetSimilarity(cellchat, type = "structural")
cellchat <- netEmbedding(cellchat, type = "structural")
#> Manifold learning of the signaling networks for a single dataset
cellchat <- netClustering(cellchat, type = "structural", do.parallel = FALSE)
#> Classification learning of the signaling networks for a single dataset
# Visualization in 2D-space
netVisual_embedding(cellchat, type = "structural", label.size = 3.5)
```

```{r}
saveRDS(cellchat, "./revisedDataset/rds/scRNA_FLCnew-trunc0.15.rds")
```