---
title: "Six FLC and 4 NML"
output: html_document
date: "2023-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}
# library(Matrix)cd /
library(stringr)
library(Seurat)
library(tidyverse)
library(openxlsx)
library(scDblFinder)
library(BiocParallel)
# BiocManager::install("glmGamPoi")
```

```{r}
install.packages('installr')
library(installr)
install.Rtools()
install.packages('Matrix')
library(Matrix)
```

```{r set project}
set.seed(1234)
proj_name <- "FLCvNML"
```

```{r Load-data}
##Setup the Seurat objects

# Load the counts matricies into separate datasets
## NML
N008.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_N008_filt/")
N014.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_N014_filt/")
N015.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_N015_filt/")
N021.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_N021_filt/")

## FLC
T005.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_T005_filt//")
T008.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_T008_filt/")
T014.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_T014_filt/")
T021.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_T021_filt/") 
T034.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_T034_filt/")
T038.data <- Read10X(data.dir = "./soupx-adj-counts/soupx_T038_filt/")

# check for duplicated barcodes(column names) within a dataset
## NML
any(duplicated(x = colnames(x = N008.data))) # FALSE
any(duplicated(x = colnames(x = N014.data))) # FALSE
any(duplicated(x = colnames(x = N015.data))) # FALSE
any(duplicated(x = colnames(x = N021.data))) # FALSE

## FLC
any(duplicated(x = colnames(x = T005.data))) # FALSE
any(duplicated(x = colnames(x = T008.data))) # FALSE
any(duplicated(x = colnames(x = T014.data))) # FALSE
any(duplicated(x = colnames(x = T021.data))) # FALSE
any(duplicated(x = colnames(x = T034.data))) # FALSE
any(duplicated(x = colnames(x = T038.data))) # FALSE


# Rename columns to avoid trouble when merging data sets (since identical columns between KO and WT)
## NML
colnames(x = N008.data) <- paste('NML_N008', colnames(x = N008.data), sep = '_')
colnames(x = N014.data) <- paste('NML_N014', colnames(x = N014.data), sep = '_')
colnames(x = N015.data) <- paste('NML_N015', colnames(x = N015.data), sep = '_')
colnames(x = N021.data) <- paste('NML_N021', colnames(x = N021.data), sep = '_')

## FLC
colnames(x = T005.data) <- paste('FLC_T005', colnames(x = T005.data), sep = '_')
colnames(x = T008.data) <- paste('FLC_T008', colnames(x = T008.data), sep = '_')
colnames(x = T014.data) <- paste('FLC_T014', colnames(x = T014.data), sep = '_')
colnames(x = T021.data) <- paste('FLC_T021', colnames(x = T021.data), sep = '_')
colnames(x = T034.data) <- paste('FLC_T034', colnames(x = T034.data), sep = '_')
colnames(x = T038.data) <- paste('FLC_T038', colnames(x = T038.data), sep = '_')
```

```{r Create Seurat Object}
### Initialize the Seurat object with the raw, non-normalized data
# Keep all genes expressed in >= 3 cells. 
# Keep all cells with at least 200 detected genes.
N008 <- CreateSeuratObject(counts = N008.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "N008")
N014 <- CreateSeuratObject(counts = N014.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "N014")
N015 <- CreateSeuratObject(counts = N015.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "N015")
N021 <- CreateSeuratObject(counts = N021.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "N021")
T005 <- CreateSeuratObject(counts = T005.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "T005")
T008 <- CreateSeuratObject(counts = T008.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "T008")
T014 <- CreateSeuratObject(counts = T014.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "T014")
T021 <- CreateSeuratObject(counts = T021.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "T021")
T034 <- CreateSeuratObject(counts = T034.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "T034")
T038 <- CreateSeuratObject(counts = T038.data, 
                            min.cells = 3, 
                            min.features = 200, 
                            project = "T038")
```

```{r Add group status to Seurat objects}
### add treatment/group status to objects
# add group
N008[["status"]] <- "NML"
N014[["status"]] <- "NML"
N015[["status"]] <- "NML"
N021[["status"]] <- "NML"
T005[["status"]] <- "FLC"
T008[["status"]] <- "FLC"
T014[["status"]] <- "FLC"
T021[["status"]] <- "FLC"
T034[["status"]] <- "FLC"
T038[["status"]] <- "FLC"

N008[["id"]] <- "N008"
N014[["id"]] <- "N014"
N015[["id"]] <- "N015"
N021[["id"]] <- "N021"
T005[["id"]] <- "T005"
T008[["id"]] <- "T008"
T014[["id"]] <- "T014"
T021[["id"]] <- "T021"
T034[["id"]] <- "T034"
T038[["id"]] <- "T038"

N008
N014
N015
N021
T005
T008
T014
T021
T034
T038
```

```{r Merge dataset, cache = T}
set.seed(1234)

# Merge datasets into one single seurat object
alldata <- merge(N008, y = c(N014, N015, N021, 
                             T005, T008, T014, T021, T034, T038), 
                 add.cell.ids = c("N008", "N014", "N015", "N021", 
                             "T005", "T008", "T014", "T021", "T034", "T038"),
                 project = "fullFLC")

alldata

# Convert to single cell experiment
sce <- as.SingleCellExperiment(alldata)
```

```{r Save SCE}
dir.create("./revisedDataset")
dir.create("./revisedDataset/rds")
```

```{r Run scDoubletFinder}
dir.create("./revisedDataset/csv")
bp <- MulticoreParam(80, RNGseed=1234)
bpstart(bp)
sce <- scDblFinder(sce, 
                   samples="id", 
                   BPPARAM=bp)

bpstop(bp)

# If the code above doesn't work, unhash and try this.

#sce <- scDblFinder(sce,
#                   samples="id",
#                   BPPARAM=MulticoreParam(3))

table(sce$scDblFinder.class)

# Write out metadata of doublet scores to flat file
sce@colData %>% 
  as.data.frame() %>%
  rownames_to_column(var = "cell_id") %>%
  dplyr::select(cell_id, contains("scDblFinder")) %>%
  write_csv(paste0("./revisedDataset/csv/", proj_name, "_scDbtFinder_metadata.csv"))

sce_sub <- subset(sce, ,scDblFinder.class=="singlet")
table(sce_sub$scDblFinder.class)

singlet_cell_id <- colnames(sce_sub)
```

```{r}
for (i in 1:length(singlet_cell_id)) {
  singlet_cell_id[i] <- substr(singlet_cell_id[i], 6, nchar(singlet_cell_id[i]))
}
```

```{r}
saveRDS(sce, "./revisedDataset/rds/sce.rds")
saveRDS(alldata, "./revisedDataset/rds/alldata.rds")
# sce <- readRDS("./revisedDataset/rds/sce.rds")
# alldata <- readRDS("./revisedDataset/rds/alldata.rds")
```

```{r}
# Visualize QC metrics as a violin plot
VlnPlot(alldata, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.

plot1 <- FeatureScatter(alldata, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(alldata, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
```

### QC and filtering

```{r qc-and-filtering, fig.width = 5, fig.height = 6}
set.seed(1234)
dir.create("./revisedDataset/QualityControl")
# Calculate percentage of mitochondrial counts
obj.list <- list(N008, N014, N015, N021, T005, T008, T014, T021, T034, T038)

# Remove cells classified as doublets by scDblFinder
for (i in 1:length(obj.list)) {
  print(obj.list[[i]]@project.name)
  print(paste0("Number of cells: ", ncol(obj.list[[i]])))
  obj.list[[i]] <- obj.list[[i]][,intersect(colnames(obj.list[[i]]), singlet_cell_id)]
  print(paste0("Number of cells: ", ncol(obj.list[[i]])))
  print(" ")
}

# Add % of reads mapping to mitochondrial genes
for (i in 1:length(obj.list)) {
  obj.list[[i]] <- PercentageFeatureSet(obj.list[[i]], pattern = "^MT-", col.name = 'percent.mt') 
  obj.list[[i]][["per.mito.bin"]] <- ifelse(obj.list[[i]][["percent.mt"]] > 20, "> 20%", ifelse(obj.list[[i]][["percent.mt"]] > 10, "10%-20%", ifelse(obj.list[[i]][["percent.mt"]] > 2.5, "2.5%-10%", "< 2.5%")))
}

# Visualize QC metrics as a violin plot
plts <- lapply(obj.list, function(x) VlnPlot(x, 
                                             features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), 
                                             group.by = "id",
                                             pt.size = 0,
                                             ncol = 3))

patchwork::wrap_plots(plts, ncol = 1)
ggsave(paste0("./revisedDataset/QualityControl/", proj_name, "_QC_no-pts.png"), units = "in", width = 6, height = 4 * length(obj.list), dpi = 300)

plts <- lapply(obj.list, function(x) VlnPlot(x, 
                                             features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), 
                                             group.by = "id",
                                             pt.size = 0.25,
                                             ncol = 3))

patchwork::wrap_plots(plts, ncol = 1)
ggsave(paste0("./revisedDataset/QualityControl/", proj_name, "_QC.png"), units = "in", width = 6, height = 4 * length(obj.list), dpi = 300)

# Subset loop

for (i in 1:length(obj.list)) {
  print(obj.list[[i]]@project.name)
  print(paste0("Number of cells: ", ncol(obj.list[[i]])))
  obj.list[[i]] <- subset(obj.list[[i]], subset = nFeature_RNA > 1000 & percent.mt < 20)
  print(paste0("Number of cells: ", ncol(obj.list[[i]])))
  print(" ")
}
```

```{r scDblFinder results}
[1] "N008"
[1] "Number of cells: 21713"
[1] "Number of cells: 18130"
[1] " "
[1] "N014"
[1] "Number of cells: 16844"
[1] "Number of cells: 14662"
[1] " "
[1] "N015"
[1] "Number of cells: 17425"
[1] "Number of cells: 14426"
[1] " "
[1] "N021"
[1] "Number of cells: 20046"
[1] "Number of cells: 17637"
[1] " "
[1] "T005"
[1] "Number of cells: 25734"
[1] "Number of cells: 22116"
[1] " "
[1] "T008"
[1] "Number of cells: 23090"
[1] "Number of cells: 18612"
[1] " "
[1] "T014"
[1] "Number of cells: 27915"
[1] "Number of cells: 23717"
[1] " "
[1] "T021"
[1] "Number of cells: 19214"
[1] "Number of cells: 16820"
[1] " "
[1] "T034"
[1] "Number of cells: 24953"
[1] "T038"
[1] "Number of cells: 5026"
[1] "Number of cells: 4676"
[1] " "
```

```{r QC results}
[1] "N008"
[1] "Number of cells: 18130"
[1] "Number of cells: 14503"
[1] " "
[1] "N014"
[1] "Number of cells: 14662"
[1] "Number of cells: 6625"
[1] " "
[1] "N015"
[1] "Number of cells: 14426"
[1] "Number of cells: 12491"
[1] " "
[1] "N021"
[1] "Number of cells: 17637"
[1] "Number of cells: 14132"
[1] " "
[1] "T005"
[1] "Number of cells: 22116"
[1] "Number of cells: 14172"
[1] " "
[1] "T008"
[1] "Number of cells: 18612"
[1] "Number of cells: 10388"
[1] " "
[1] "T014"
[1] "Number of cells: 23717"
[1] "Number of cells: 14875"
[1] " "
[1] "T021"
[1] "Number of cells: 16820"
[1] "Number of cells: 9412"
[1] " "
[1] "T034"
[1] "Number of cells: 21585"
[1] "Number of cells: 10994"
[1] " "
[1] "T038"
[1] "Number of cells: 4676"
[1] "Number of cells: 3541"
[1] " "
```

```{r}
N008 <- obj.list[[1]]
N014 <- obj.list[[2]]
N015 <- obj.list[[3]]
N021 <- obj.list[[4]]
T005 <- obj.list[[5]]
T008 <- obj.list[[6]]
T014 <- obj.list[[7]]
T021 <- obj.list[[8]]
T034 <- obj.list[[9]]
T038 <- obj.list[[10]]

newdata <- merge(N008, y = c(N014, N015, N021,
                            T005, T008, T014, T021, T034, T038), 
                 add.cell.ids = c("N008", "N014", "N015", "N021", 
                                  "T005", "T008", "T014", "T021", "T034", "T038"),
                 project = "fullFLC")
saveRDS(newdata, "./revisedDataset/rds/newcombineddata.rds")
# newdata <- readRDS("./revisedDataset/rds/newcombineddata.rds")
```

```{r}
flc.list <- SplitObject(newdata, split.by = "status")
```

```{r}
nml <- flc.list[["NML"]]
flc <- flc.list[["FLC"]]
```

```{r}
set.seed(1234)
# normalize and run dimensionality reduction on control dataset
nml <- SCTransform(nml, vst.flavor = "v2", verbose = FALSE, new.assay.name = "SCT") %>%
    RunPCA(npcs = 30, verbose = FALSE) %>%
    RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
    FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
    FindClusters(resolution = 0.2, verbose = FALSE)

p1 <- DimPlot(nml, label = T, repel = T) + ggtitle("Unsupervised clustering")
p1 

dir.create("./revisedDataset/UMAPs")
dir.create("./revisedDataset/UMAPs/res-iter")

for (i in seq(.05, .5, by = .05)) {
  nml_tmp <- FindClusters(nml, resolution = i)
  DimPlot(nml_tmp, reduction = "umap", label = T)
  ggsave(paste0("./revisedDataset/UMAPs/res-iter/", proj_name, '_res-iter_', i, '_umap.png'), units = 'in', width = 6, height = 5, dpi = 250)
}

nml <- FindClusters(nml, resolution = 0.2)
DefaultAssay(nml) <- "SCT"

saveRDS(nml, paste0("./revisedDataset/rds/", proj_name, '_nml-obj.rds'))
# nml <- readRDS("rds/FLCvNMLnml-obj.rds")
```

```{r}
flc <- SCTransform(flc, vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE)
saveRDS(flc, paste0("./revisedDataset/rds/", proj_name, '_flc-obj.rds'))
flc <- readRDS("./revisedDataset/rds/FLCvNML_flc-obj.rds")
flc.list <- list(nml = nml, flc = flc)
features <- SelectIntegrationFeatures(object.list = flc.list, nfeatures = 3000)
flc.list <- PrepSCTIntegration(object.list = flc.list, anchor.features = features)
saveRDS(flc.list, paste0("./revisedDataset/rds/", proj_name, '_PrepSCTInt-obj.rds'))
# flc.list <- readRDS("rds/FLCvNML_PrepSCTInt-obj.rds")
```

```{r}
flc.anchors <- FindIntegrationAnchors(object.list = flc.list, normalization.method = "SCT",
    anchor.features = features)
saveRDS(flc.anchors, paste0("./revisedDataset/rds/", proj_name, '_FLCanchors-obj.rds'))
# flc.anchors <- readRDS("./fullDards/FLCvNML_FLCanchors-obj.rds")
```

```{r}
flc.combined.sct <- IntegrateData(anchorset = flc.anchors, normalization.method = "SCT")
saveRDS(flc.combined.sct, paste0("./revisedDataset/rds/", proj_name, '_integratedData-obj.rds'))
# flc.combined.sct <- readRDS("decoupled-integration/rds/FLCvNML_integratedData-obj.rds")
```

```{r}
flc.combined.sct <- RunPCA(flc.combined.sct, verbose = FALSE)
flc.combined.sct <- RunUMAP(flc.combined.sct, reduction = "pca", dims = 1:30, verbose = FALSE)
flc.combined.sct <- FindNeighbors(flc.combined.sct, reduction = "pca", dims = 1:30)
flc.combined.sct <- FindClusters(flc.combined.sct, resolution = 0.3)
```

```{r}
saveRDS(flc.combined.sct, paste0("./revisedDataset/rds/", proj_name, '_Neighbors.rds'))
# flc.combined.sct <- readRDS("./revisedDataset/rds/FLCvNML_Neighbors.rds")
```

```{r}
DimPlot(flc.combined.sct, reduction = "umap", split.by = "status", raster = FALSE)
DimPlot(flc.combined.sct, reduction = "umap", label = T, raster = FALSE)
```

```{r}
dir.create("./revisedDataset/UMAPs/res-iter/scTransform")

for (i in seq(.05, .5, by = .05)) {
  flc.combined_tmp <- FindClusters(flc.combined.sct, resolution = i)
  DimPlot(flc.combined_tmp, reduction = "umap", label = T, raster = FALSE)
  ggsave(paste0("./revisedDataset/UMAPs/res-iter/scTransform/", proj_name, '_res-iter_', i, '_umap-scTransform-noRaster.png'), units = 'in', width = 6, height = 5, dpi = 250)
}

flc.combined.sct <- FindClusters(flc.combined.sct, resolution = 0.2)
```

```{r UMAP-plot, fig.width=6, fig.height=10}
### Make UMAP plots

dir.create("./revisedDataset/UMAPs/metadata")
dir.create("./revisedDataset/UMAPs/metadata/scTransform")

plt1 <- DimPlot(flc.combined.sct, reduction = "umap", label = T, raster = FALSE)
plt2 <- DimPlot(flc.combined.sct, reduction = "umap", group.by = "status", raster = FALSE)
plt3 <- DimPlot(flc.combined.sct, reduction = "umap", group.by = "id", raster = FALSE)
plt4 <- DimPlot(flc.combined.sct, reduction = "umap", split.by = "status", raster = FALSE)
plt1 / plt2 / plt3 / plt4

ggsave(paste0("./revisedDataset/UMAPs/metadata/scTransform/", proj_name, '_umap-metadata-noRaster.png'), units = 'in', width = 5, height = 15, dpi = 250)
```

## Harmony Integration

Since it appears that the clusters present in my dataset are patient specific, I will integrate them using Harmony as I have done for snATAC-seq. This is to be done after running PCA on the merged SCTransformed dataset.

```{r}
library(harmony)
```

```{r}
harmonized_seurat <- RunHarmony(flc.combined.sct, 
				group.by.vars = c("id"), 
				reduction = "pca", assay.use = "SCT", reduction.save = "harmony")

harmonized_seurat@reductions
```

```{r Do UMAP and clustering using Harmony embeddings}
harmonized.seurat <- harmonized_seurat %>% 
  RunUMAP(reduction = "harmony", dims = 1:30) %>% 
  FindNeighbors(reduction = "harmony", dims = 1:30) %>% 
  FindClusters(resolution = 0.2)
```

```{r Visualize}
dir.create("./revisedDataset/metadata/harmony")

plt1 <- DimPlot(harmonized.seurat, reduction = "umap", label = T, raster = FALSE)
plt2 <- DimPlot(harmonized.seurat, reduction = "umap", group.by = "status", raster = FALSE)
plt3 <- DimPlot(harmonized.seurat, reduction = "umap", group.by = "id", raster = FALSE)
plt4 <- DimPlot(harmonized.seurat, reduction = "umap", split.by = "status", raster = FALSE)
plt1 / plt2 / plt3 / plt4

ggsave(paste0("./revisedDataset/UMAPs/metadata/harmony/", proj_name, '_umap-metadata-noRaster.png'), units = 'in', width = 6, height = 15, dpi = 250)
```

```{r}
dir.create("./revisedDataset/UMAPs/res-iter/harmony")

for (i in seq(.05, .3, by = .05)) {
  harmonized.tmp <- FindClusters(harmonized.seurat, resolution = i)
  DimPlot(harmonized.tmp, reduction = "umap", label = T, raster = FALSE)
  ggsave(paste0("./revisedDataset/UMAPs/res-iter/harmony/", proj_name, '_res-iter_', i, '_umap-scTransform-Harmonized.png'), units = 'in', width = 6, height = 5, dpi = 250)
}

harmonized.seurat <- FindClusters(harmonized.seurat, resolution = 0.15)
```

```{r}
saveRDS(harmonized.seurat, paste0("./revisedDataset/rds/", proj_name, '_harmonized-byID-obj.rds'))
# harmonized.seurat <- readRDS('./revisedDataset/rds/FLCvNML_harmonized-byID-obj.rds')
```

```{r cell-abundances}
### Find cell #/% in each cluster and right output
dir.create("./revisedDataset/proportions")

count_per_cluster <- table(Idents(harmonized.seurat), harmonized.seurat@meta.data$status)
percent_per_cluster <- prop.table(table(Idents(harmonized.seurat), harmonized.seurat@meta.data$status), margin = 2)

count_per_cluster
percent_per_cluster

as.data.frame(percent_per_cluster) %>%
  mutate(Percent = Freq * 100,
         Cluster = Var1,
         Condition = Var2) %>%
  ggplot(., aes(Cluster, Percent, fill = Condition)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  theme_classic()
  ggsave(paste0("./revisedDataset/proportions/", proj_name, '_percent_cell_in_cluster.png'), width = 8, height = 6)

as.data.frame(prop.table(table(Idents(harmonized.seurat), harmonized.seurat@meta.data$status), margin = 1)) %>%
    mutate(Percent = Freq * 100,
         Cluster = Var1,
         Condition = Var2) %>%
  ggplot(., aes(Cluster, Percent, fill = Condition)) +
  geom_bar(stat = 'identity') +
  theme_classic()
  ggsave(paste0("./revisedDataset/proportions/", proj_name, '_percent_sample_in_cluster.png'), width = 8, height = 6)


wb=createWorkbook()
ws=addWorksheet(wb,'Cells per cluster')
writeData(wb, ws, count_per_cluster, rowNames = F, colNames = T, startRow = 1,startCol = 1)
ws=addWorksheet(wb,'Percent per cluster')
writeData(wb, ws, percent_per_cluster, rowNames = F, colNames = T, startRow = 1,startCol = 1)
saveWorkbook(wb, paste0("./revisedDataset/proportions/", proj_name, '_cells_per_cluster.xlsx'), overwrite = T)
```

```{r}
metadata <- harmonized.seurat@meta.data
DefaultAssay(harmonized.seurat) <- "SCT"
```

```{r}
# These are now standard steps in the Seurat workflow for visualization and clustering
# Visualize canonical marker genes as violin plots.
dir.create("./revisedDataset/UMAPs/UMAPoverlays")
"" %in% rownames(harmonized.seurat@assays$RNA@counts)

VlnPlot(harmonized.seurat, features = c("VCAN", "SLC16A14", "PDE10A", "TMEM163", "OAT", "CA12", "BACE2", "COL4A1"),
    pt.size = 0.2, ncol = 4)

ggsave(paste0("./revisedDataset/UMAPs/UMAPoverlays/", proj_name, "_FLC-markerGenes-SCT.png"), units = "in", width = 15, height = 10, dpi = 300)
```

```{r}
# Visualize canonical marker genes on the sctransform embedding.
FeaturePlot(harmonized.seurat, features = c("VCAN", "SLC16A14", "PDE10A", "TMEM163", "OAT", "CA12", "BACE2", "COL4A1", raster = FALSE), pt.size = 0.2,
    ncol = 4)

ggsave(paste0("./revisedDataset/UMAPs/UMAPoverlays/", proj_name, "_FLC-markerGenes-featurePlots-integrated.png"), units = "in", width = 18, height = 10, dpi = 300)
```

```{r}
DimPlot(harmonized.seurat, reduction = "umap", split.by = "status")

FeaturePlot(harmonized.seurat, features = c("VCAN", "SLC16A14", "PDE10A", "TMEM163", "OAT", "CA12", "BACE2", "COL4A1"), pt.size = 0.2,
            split.by = "status",
            ncol = 4,
            raster = FALSE)

ggsave(paste0("./revisedDataset/UMAPs/UMAPoverlays/", proj_name, "_FLC-markerGenes-featurePlots-integrated-byStatus.png"), units = "in", width = 18, height = 20, dpi = 300)
```

```{r}
DefaultAssay(harmonized.seurat) <- "SCT"
for (gene in c("VCAN", "SLC16A14", "PDE10A", "TMEM163", "OAT", "CA12", "BACE2", "COL4A1", "CA12", "PDGFB", "PDGFRB", "TGFB3", "TGFBR2", "TGFB3", "TGFBR1", "KLF4", "WNT4", "FZD10", "BACE2", "FAM167A", "GPRIN3", "IRF4", "KIF26B", "PDE10A")) {
  FeaturePlot(harmonized.seurat, 
              features = gene, 
              pt.size = 0.2, 
              split.by = "status", 
              ncol = 4,
              raster = FALSE,
              label = TRUE)
  ggsave(paste0("./revisedDataset/UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-named.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```

```{r}
DefaultAssay(harmonized.seurat) <- "SCT"
for (gene in c("GLI1", "GLI2", "GLI3", "BAG2", "STIP1")) {
  FeaturePlot(harmonized.seurat, features = gene, pt.size = 0.2, split.by = "status", ncol = 4, label = TRUE)
  ggsave(paste0("UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-SCT-named.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```

```{r}
DefaultAssay(harmonized.seurat) <- "SCT"
for (gene in c("SOX17")) {
  FeaturePlot(harmonized.seurat, features = gene, pt.size = 0.2, split.by = "status", ncol = 4, label = TRUE)
  ggsave(paste0("./revisedDataset/UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-SCT-named.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```

```{r}
DefaultAssay(harmonized.seurat) <- "SCT"
for (gene in c("VEGFA")) {
  FeaturePlot(harmonized.seurat, features = gene, pt.size = 0.2, split.by = "status", ncol = 4, label = TRUE)
  ggsave(paste0("./revisedDataset/UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-SCT-named.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```

## Session info

```{r session-info}
sessionInfo()
```
