---
title: "FLC snRNA-seq clustering"
author: "Alaa R. Farghli"
date: "Last compiled on `r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: 
    toc: true
    toc_float: true
    theme: flatly
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}
library(Seurat)
library(tidyverse)
```
# Single cell RNAseq analysis

This is the continued single nuclei RNAseq analysis of FLC provided by the Khasayer lab.

## Seurat analysis

### Find markers

```{r find-markers, warning=F, message=F}
set.seed(1234)
proj_name <- "FLCvNML"
```

```{r}
harmonized.seurat <- readRDS(paste0("rds/", proj_name, '_harmonized-byID-obj.rds'))
Idents(harmonized.seurat) <- "seurat_clusters"
levels(harmonized.seurat)
```

```{r}
new.cluster.ids <- c("Epithelial", #0
  "Mixed", #1
  "Epithelial", #2
  "Endothelial", #3
  "Stellate", #4
  "Epithelial-like", #5
  "Epithelial",  #6
  "Macrophages",  #7
  "Lymphocytes",  #8
  "Epithelial",  #9
  "Unknown", #10
  "Unknown") #11
  
names(new.cluster.ids) <- levels(harmonized.seurat)
harmonized.seurat <- RenameIdents(harmonized.seurat, new.cluster.ids)
DimPlot(harmonized.seurat, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
```

```{r}
ggsave(paste0("UMAPs/UMAPoverlays/", proj_name, "_umap_clusterNamed.png"), units = 'in', width = 6, height = 6, dpi = 250)
```

```{r}
DefaultAssay(harmonized.seurat) <- "integrated"
for (gene in c("SOX17", "GLS", "PDGFB", "PDGFRB", "WNT4", "FZD10", "VEGFA", "TGFB3", "TGFBR2", "TGFBR1", "KDR", "FLT1", "CTLA4")) {
  FeaturePlot(harmonized.seurat, features = gene, pt.size = 0.2, split.by = "status", ncol = 4)
  ggsave(paste0("UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-integrated.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```

```{r}
DefaultAssay(harmonized.seurat) <- "RNA"
for (gene in c("CXCR4", "CXCL12", "BAG2")) {
  FeaturePlot(harmonized.seurat, features = gene, pt.size = 0.2, split.by = "status", ncol = 4)
  ggsave(paste0("UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-RNA.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```

```{r}
DefaultAssay(harmonized.seurat) <- "RNA"
for (gene in c("OAT", "OTC", "LDHB", "SDS", "GLS", "ALDH18A1", "PYCR1", "PYCR2", "PRODH", "P4HA2")) {
  FeaturePlot(harmonized.seurat, features = gene, pt.size = 0.2, split.by = "status", ncol = 4)
  ggsave(paste0("UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-RNA.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```

```{r}
DefaultAssay(harmonized.seurat) <- "SCT"
for (gene in c("VCAN", "SLC16A14")) {
  FeaturePlot(harmonized.seurat, features = gene, pt.size = 0.2, split.by = "status", ncol = 4, label = TRUE)
  ggsave(paste0("UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-SCT-named.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```

```{r}
DefaultAssay(harmonized.seurat) <- "SCT"
for (gene in c("GLI1", "GLI2", "GLI3", "BAG2", "STIP1")) {
  FeaturePlot(harmonized.seurat, features = gene, pt.size = 0.2, split.by = "status", ncol = 4, label = TRUE)
  ggsave(paste0("UMAPs/UMAPoverlays/", proj_name, "_", gene, "-featurePlot-integrated-byStatus-SCT-named.png"), units = "in", width = 18, height = 10, dpi = 300)
}
```
